### ISSUE TITLE
Plex plugin does not respect Series Name Choice of JMM

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/plexplugin#11]
The Plex plugin does not respect Series Name Choice of JMM.
The Plex plugin ATM does not care witch way you want your series names, it always chooses Romanization over what your chose, may it be Localized (like i like it) or any other ways.
JMM itself supports this choice, shouldnt it be the same across all JMM apps?

**Comment by maxpiva** [comment]
True, plex have some problems with japanese encodings on my tests.

**Comment by AreFinstad** [comment]
well i can get that Japanese Characters can be a problem and such, but i dont see why it would not work with the Localized Series names in English instead of Romanization.
yes yes, Romanization is Japanese with English Letters and so on..... but i would rather have the english name myself XD

**Comment by AreFinstad** [comment]
well i can get that Japanese Characters can be a problem and such, but i dont see why it would not work with the Localized Series names in English instead of Romanization.
yes yes, Romanization is Japanese with English Letters and so on..... but i would rather have the english name myself XD

**Comment by maxpiva** [comment]
If i remember correctly i have also some problems also with the MovieDB
title not forwarded, in the latest version (svn one, this one remove some
level of hierarchy, on the plex client) (Complete Movie is not a nice name
;)  , anyway. I don't think i will handle it right now. The way contracts
between clients and server, need some refactor first, and probably the DB
backend. JMM grow a lot, and some refactoring maybe needed :)

**Comment by maxpiva** [comment]
Should be fixed but need testing
