### ISSUE TITLE
Plex Agent fails when changing audio stream and subtitles

### ISSUE THREAD

**Issue by trillex** [japanesemediamanager/plexplugin#12]
Whenever I try to change a movie/series with several audio streams and/or subtitles, it will tell me the following: 

There was a problem selecting the stream for this item.

I can't get the Plex Web player to provide any logs of this other than the fact that an ajax window popped up with an error, so I'm unsure where the issue might lie.

**Comment by maxpiva** [comment]
It's a Plex Limitation, jmm plugin is a kinda hack. Plex Channels do not support subtitles and or multiple streams, scrobble also do not work.  Last time i check It only works for their own stuff.
