### ISSUE TITLE
[Enchancement] Scanner and Media agent for Plex

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/plexplugin#14]
I've started making a scanner agent and metadata agent for Plex, for now it uses same API as the channel plugin does. I've got basic stuff working, shows, seasons, episodes, show poster. No support for groups yet and no episode/series metadata. 
Scanner is needed to use JMM data when adding files to shows, standard series scanner will not recognize the situation when 2 shows are in same folder and other issues.

Will you be interested in that?

I've tried using channel but it is crashing on Plex for Android for some reason, and I don't like the fact that I can't track watched status in a channel like I can in a library.

**Comment by AreFinstad** [comment]
i for one would love a scanner agent. would be much more stable in many ways. would it still be limited to plex way of folder setup?

**Comment by hidden4003** [comment]
Yes and no. 
It uses file path for matching, Plex library and JMM forders has to be the same. It can be changed to relative paths with little effort. With relative path only folder structure would have to be same but then again why would you want 2 copies of your collection.  In my setup it is same folder, so first it builds list of files that JMM knows then assigns metadata according to this list.
Since JMM uses file hash to determine what show file belongs to folder structure is no longer critical you can put all seasons on same show + specials in one folder.
For me it solved a problem where I had 2 seasons, 1 ova and specials all in one folder now I see those as 3 separate shows as I wanted in the beginning.

**Comment by maxpiva** [comment]
If you want to provide extra functionality to the agent, please look at the plex services in JMMServer.
About, the scrobbling, probably, it'll be easier for us,  maintain the % read from the webservice, and after 95-99% mark it as read. Since plex, still, doesn't support scrobbling channels.
