### ISSUE TITLE
Plex has stopped

### ISSUE THREAD

**Issue by SaiZaro** [japanesemediamanager/plexplugin#15]
Ok have an issue with Plex, whatever I try to open any series I getting message 'Unfortunately, Plex has stopped.' on my Android. It was working a few months ago just fine.

**Comment by ElementalCrisis** [comment]
Just tried and I get the same error, I don't use Plex so I don't have any other plugins but besides this plugin, does everything else work normally.

**Comment by SaiZaro** [comment]
Yes everything else working fine, just JMM plugin crashes when I try and open an anime, I don't even see episodes just when I tap anime it crashes.

**Comment by maxpiva** [comment]
Gonna try later on a Fire TV, did you use the latest version of the plugin, from HERE (repository). and latest version of JMM Server?
I don't know if the latest patches for android version got a release.

**Comment by SaiZaro** [comment]
JMM Server is the latest version (I formatted my PC recently so I get fresh installation)

And I tried version from Plex forum, from here as well as website, same issue.

**Comment by maxpiva** [comment]
use the one here, in github, anyway, gonna check it on the Fire TV this evening.

**Comment by AreFinstad** [comment]
on note, works fine on the server webpage, Toshiba Smart TV app, PlexHT, iOS official app and plex constellation for iOS. dont have an android device to test it on tho sadly.

**Comment by SaiZaro** [comment]
Wired thing is that I can cast to my devices and its working, but I can't play it using (control it) via those devices.

Using version from github and all my stuff is up to dated, using Note 3 phone and Tab 3 tablet, apart from JMM Plex on android everything working fine.

**Comment by TempleClause** [comment]
I had the same problem. 
I solved it by changing a setting on my android phone:
Video -> scroll down to Advanced -> untick "Use experimental player" 

No idea why this is the default setting...

**Comment by SaiZaro** [comment]
hmm i tried you suggestion and still the same problem, everything else is working just not this one. Tried a few other things that i found on the forum but none of them worked out, any other suggestions to try?

**Comment by maxpiva** [comment]
Saizaro, Could you post plex log files and jmmserver log files. Thanks

**Comment by SaiZaro** [comment]
kk question, where I can find log files for plex (android)?

**Comment by maxpiva** [comment]
Hmm plex server.

**Comment by LiudvikasT** [comment]
I am having this issue as well.
Plugin logs as such: http://pastebin.com/MZXrWeQq
Server logs: http://pastebin.com/2fu0NMZz
And jmmserver logs: http://pastebin.com/jrfNWqme

**Comment by maxpiva** [comment]
I dont see anything strange in the logs, seems somehow android version
choke parsing jmm server xml. Last time i check my fire tv was working
right.Could you be so kind and get me the android version running?

**Comment by LiudvikasT** [comment]
I am running 5.1.1 android.

**Comment by maxpiva** [comment]
Hmm, i mean plex android version. (The plex client). sorry

**Comment by maxpiva** [comment]
I just tested Plex on Fire TV (Android Plex Client Version 4.20.0.522).
Checked several anime series, and no problem whatsover. This occurs on
every series in your setups?

**Comment by LiudvikasT** [comment]
It's the same version: 4.20.0.522. And yes it does occur on every series.

**Comment by LiudvikasT** [comment]
I just found out that if I try to play an episode through "Unsort" then it works.

**Comment by LiudvikasT** [comment]
If it helps this is the log from android app:
http://pastebin.com/2i8pGRfw

**Comment by maxpiva** [comment]
It helps a lot, some data is missing in the xml, and it seems the android client try to uppercase a null string, i'll decompile the android client, to single out the offending field.

**Comment by maxpiva** [comment]
Does this happens, on android with a Different language than English ????

Seems, the null uppercase is a reference to a internal string... Please can
you test in english is this happens.

If in english is not happening, is for sure a missing translation in the
plex android version, and should be reported to plex devs.

**Comment by LiudvikasT** [comment]
My phone is in english, plex app also. I am not aware of a way to change the apps language, can't find it in settings. Changing the systems language doesn't seem to change the language of the app.

**Comment by maxpiva** [comment]
Nevermind, decompiled the wrong class, found the culprit. Android version
expect ParentTitle to be filled all the time. Next version will fix it.
Sorry, but you have to wait,  since, there is other features in the
pipeline. (plex user mapping to jmm users, and watch status on JMM)

**Comment by maxpiva** [comment]
fixed in last version

**Comment by clienthax** [comment]
So,
I'm using the recommended version and getting a crash when opening the channel on android,
Is it patched in the recommended?

**Comment by ElementalCrisis** [comment]
Hello, 

The current version is 3.5.0.2, http://jmediamanager.org/downloads/. Is that the version you are using? Might be best to create a new thread, post what you were doing prior to the crash as well as your logs.
