### ISSUE TITLE
Plugin does not work with official plex app on Toshiba Smart TV

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/plexplugin#16]
the app can browse the series, filters and episodes with issues (images does not fit at all tho sadly)
whenever i try to play something it locks up and plex would say there is a problem playing this item, the video did not start playing in time.

first i thought it was a codec issue but plex plugins only stream anways so it should be an issue (dont have issues with the same codecs in normal plex libs either) 

in anycase, here is the logs. did browse a bit and then try to play two different things with the plugin. i could try more but it doesnt work.
start looking at 2015-10-07 21:43:42,313 in the log bellow.
https://drive.google.com/open?id=0B-hww4iUE6HsNE1OYUplaE9NTXc

**Comment by maxpiva** [comment]
I don't see any video call in that log. I only see browsing. maybe you
should include the main plex server log also.

Thanks

**Comment by AreFinstad** [comment]
there you go. uploaded all the logs i had there.
https://drive.google.com/open?id=0B-hww4iUE6HsS2VEcTJtT3JoN2s

**Comment by AreFinstad** [comment]
it might just be the app itself tho...... as its utter shit IMO. well the TV is in general.
tho some of the other apps do work, sometimes....

**Comment by AreFinstad** [comment]
dont have this TV anymore so i cant test any fixes or for any issues if i have to.
closing this issue, i guess we can open again if more people have issues with this tv os.
