### ISSUE TITLE
GetCurrentPlexUser throws 401 unauthorized

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/plexplugin#20]
Plex server version 0.9.16.6  (latest version at the moment of writing).

The error message is a bit misleading:
>  Error connecting to JMM Server, please verify preferences (HTTP Error 401: Unauthorized)

But in fact it is a problem with plex.tv api

Relevant logs:
> 2016-05-19 12:58:35,641 (186c) :  DEBUG (runtime:717) - Handling request GET /video/jmm
> 2016-05-19 12:58:35,642 (186c) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
> 2016-05-19 12:58:35,647 (186c) :  DEBUG (runtime:814) - Found route matching /video/jmm
> 2016-05-19 12:58:35,664 (186c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/identity'
> 2016-05-19 12:58:35,940 (186c) :  DEBUG (networking:166) - Requesting 'https://plex.tv/api/home/users'
> 2016-05-19 12:58:36,368 (186c) :  ERROR (networking:217) - Error opening URL 'https://plex.tv/api/home/users'
> 2016-05-19 12:58:36,368 (186c) :  INFO (logkit:16) - My Anime Exception: HTTP Error 401: Unauthorized
> 2016-05-19 12:58:36,371 (186c) :  DEBUG (base:117) - Checking if com.plexapp.plugins.myanime is broken
> 2016-05-19 12:58:36,371 (186c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X1N0b3JlU2VydmljZTpJc0NoYW5uZWxCcm9rZW4_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMQpzMjcKY29tLnBsZXhhcHAucGx1Z2lucy5teWFuaW1lczEwCmlkZW50aWZpZXJyMAo_'
> 2016-05-19 12:58:36,387 (186c) :  DEBUG (runtime:88) - Sending packed state data (108 bytes)
> 2016-05-19 12:58:36,387 (186c) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 1008 bytes

**Comment by ElementalCrisis** [comment]
Fix in #21.
