### ISSUE TITLE
Channel main menu crash in Plex for Android native application

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/plexplugin#23]
I've figured out the reason why the channel was crashing the Plex app for me.

in init.py inside def MainMenu(): around line 105 there is following code
> return req.content.replace('< /MediaContainer>','<Directory prompt="Search" thumb="'+R(ICON_SEARCH)+'" art="'...

On my older tablet I have root so I was able to get a stacktrace which said:

> IndexOutOfBoundsException Invalid index 5, size is 5

And that is exactly the value of <MediaContainer size="5" so this value was not adjusted when extra element was added.

I've replaced this line with: `return req.content` and I no longer have crashes, no search icon either but I prefer no search button rather than crashes :)

**Comment by maxpiva** [comment]
Will fix on the server, it will returns size+1, instead size.
