### ISSUE TITLE
Plex Plugin does not display info text about the episode correctly.

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/plexplugin#8]
Plex Plugin does not display info text about the episode correctly.
info about episodes gets displayed with certain layouts of season and series like this:
![](http://puu.sh/cwHxp/34a17cc090.jpg)

but does not display any info when entering the page of the episode like this:
![](http://puu.sh/cwHB8/721ff0fa5e.png)

this is something plex does atleast in the standard libraries it makes itself like this:
![](http://puu.sh/cwHQo/d361481100.jpg)

i think the plugin should display it, unless it cant for some reason that is.

sorry for the spoilers i might have caused to Arrow and Amnesia XD

**Comment by maxpiva** [comment]
Closed by Lastest JMM Server
